### ISSUE TITLE
On Linux Mint, installation fails with Python 3.8.10

### ISSUE THREAD

**Issue by Wikinaut** [dr-leo/PyHyphen#18]
```
pip3 install pyhyphen
Collecting pyhyphen
  Using cached PyHyphen-4.0.3.tar.gz (40 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9249b1dm/pyhyphen/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9249b1dm/pyhyphen/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-9249b1dm/pyhyphen/pip-egg-info
         cwd: /tmp/pip-install-9249b1dm/pyhyphen/
    Complete output (35 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9249b1dm/pyhyphen/setup.py", line 23, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 701, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 121, in parse_configuration
        meta.parse()
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 426, in parse
        section_parser_method(section_options)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 399, in parse_section
        self[name] = value
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 184, in __setitem__
        value = parser(value)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 515, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 349, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 848, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-install-9249b1dm/pyhyphen/src/hyphen/__init__.py", line 10, in <module>
        from .hyphenator import Hyphenator
      File "/tmp/pip-install-9249b1dm/pyhyphen/src/hyphen/hyphenator.py", line 27, in <module>
        from . import hnj
    ImportError: cannot import name 'hnj' from partially initialized module 'hyphen' (most likely due to a circular import) (/tmp/pip-install-9249b1dm/pyhyphen/src/hyphen/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

python --version
Python 3.8.10

```

**Comment by dr-leo** [comment]
I cannot replicate this. I remember similar build problems caused by
old versions of setuptools. Try a current one.

**Comment by Wikinaut** [comment]
I decided to use the alternative `pyphen` which works for me.
