### ISSUE TITLE
pip install pyhyphen => ImportError: cannot import name 'hnj' from partially initialized module 'hyphen'

### ISSUE THREAD

**Issue by MatrixManAtYrService** [dr-leo/PyHyphen#8]
pip gives me trouble when I try to install it pyhyphen:

```
❯ python3 -m venv venv
❯ source venv/bin/activate
venv ❯ pip install pyhyphen
Collecting pyhyphen
  Using cached PyHyphen-4.0.1.tar.gz (34 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/matt/2021/03/25/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pjosxdpn/pyhyphen/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pjosxdpn/pyhyphen/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-pjosxdpn/pyhyphen/pip-egg-info
         cwd: /tmp/pip-install-pjosxdpn/pyhyphen/
    Complete output (37 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pjosxdpn/pyhyphen/setup.py", line 41, in <module>
        setup(**arg_dict)
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/dist.py", line 701, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 121, in parse_configuration
        meta.parse()
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 426, in parse
        section_parser_method(section_options)
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 399, in parse_section
        self[name] = value
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 184, in __setitem__
        value = parser(value)
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 515, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 349, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-install-pjosxdpn/pyhyphen/src/hyphen/__init__.py", line 10, in <module>
        from .hyphenator import Hyphenator
      File "/tmp/pip-install-pjosxdpn/pyhyphen/src/hyphen/hyphenator.py", line 26, in <module>
        from . import dictools
      File "/tmp/pip-install-pjosxdpn/pyhyphen/src/hyphen/dictools.py", line 9, in <module>
        import appdirs
    ModuleNotFoundError: No module named 'appdirs'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I'm on Ubuntu 20.04, python 3.8.5

I can make it go further by first installing `appdirs` and `requests`, but then I get stuck on this one.

```
venv ❯ pip install pyhyphen
Collecting pyhyphen
  Using cached PyHyphen-4.0.1.tar.gz (34 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/matt/2021/03/25/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v5t8xs0c/pyhyphen/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v5t8xs0c/pyhyphen/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-v5t8xs0c/pyhyphen/pip-egg-info
         cwd: /tmp/pip-install-v5t8xs0c/pyhyphen/
    Complete output (35 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v5t8xs0c/pyhyphen/setup.py", line 41, in <module>
        setup(**arg_dict)
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/dist.py", line 701, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 121, in parse_configuration
        meta.parse()
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 426, in parse
        section_parser_method(section_options)
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 399, in parse_section
        self[name] = value
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 184, in __setitem__
        value = parser(value)
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 515, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/home/matt/2021/03/25/venv/lib/python3.8/site-packages/setuptools/config.py", line 349, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-install-v5t8xs0c/pyhyphen/src/hyphen/__init__.py", line 10, in <module>
        from .hyphenator import Hyphenator
      File "/tmp/pip-install-v5t8xs0c/pyhyphen/src/hyphen/hyphenator.py", line 27, in <module>
        from . import hnj
    ImportError: cannot import name 'hnj' from partially initialized module 'hyphen' (most likely due to a circular import) (/tmp/pip-install-v5t8xs0c/pyhyphen/src/hyphen/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Can you give me any hints about how to get it installed?  Thanks!

**Comment by dr-leo** [comment]
Try updating setuptools then retry with pip
Try $pythön setup.py install

**Comment by MatrixManAtYrService** [comment]
Oops, should have tried that first.  Yeah, that fixed it.  Thanks!

**Comment by heinebold** [comment]
Neither updating setuptools nor running setup.py directly fixed it for me. I have Python 3.8.5 and setuptools 45.2.0 on ubuntu 20.04. The pyhyphen version that my pip3 downloads is 4.0.1. Anything known to be incompatible here?

**Comment by dr-leo** [comment]
Setuptools 50.x

**Comment by slashdottir** [comment]
Using Python 3.11 I have setuptools 70.0.0 and this is happening to me. Same with setuptools 70.3.0


full stacktrace: 

```Error
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_phonetic_syllables
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jjones/src/phonetic_syllables/test_phonetic_syllables.py", line 8, in <module>
    from hyphen import Hyphenator
  File "/Users/jjones/src/phonetic_syllables/venv/lib/python3.11/site-packages/hyphen/__init__.py", line 10, in <module>
    from .hyphenator import Hyphenator
  File "/Users/jjones/src/phonetic_syllables/venv/lib/python3.11/site-packages/hyphen/hyphenator.py", line 27, in <module>
    from . import hnj
ImportError: dlopen(/Users/jjones/src/phonetic_syllables/venv/lib/python3.11/site-packages/hyphen/hnj.abi3.so, 0x0002): tried: '/Users/jjones/src/phonetic_syllables/venv/lib/python3.11/site-packages/hyphen/hnj.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jjones/src/phonetic_syllables/venv/lib/python3.11/site-packages/hyphen/hnj.abi3.so' (no such file), '/Users/jjones/src/phonetic_syllables/venv/lib/python3.11/site-packages/hyphen/hnj.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

Downgrading to python 3.10 seems to be helping....

Now it's hanging on startup because the default url is not responding: https://cgit.freedesktop.org/libreoffice/dictionaries/plain/en/

However the necessary files seem to be there on archive.org:

https://web.archive.org/web/20240229192158/https://cgit.freedesktop.org/libreoffice/dictionaries/plain/en/dictionaries.xcu


I wound up hosting the files myself on google drive and accessing them that way...

these seem to be the required files: 
dictionaries.xcu 
en_US.aff 
en_US.dic 
hyph_en_US.dic
